= Pflichtenheft
:project_name: Projektname
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren |  Vermerk
|0.1     | In Arbeit   | 28.10.2021          | Dan Nguyen, Konrad Schneider, Lennart Obermüller, Lisa-Marie Müller, Mohamad Alibrahim, Rosa Splittgerber
| Alle Inhalte vom Pflichtenheft wurden gemeinsam in der Gruppe erarbeitet und in einem Google-Document zusammengestellt. Ein Mitglied, dass einige Inhalte auf GitHub hochlädt, repräsentiert nicht unbedingt den Hauptautor dieser Inhalte.
|===

== Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.
//um einen Kapiteltitel zu referenzieren, fügt man den Titel in Doppelspitzeklammmer.

<<Nicht-Funktionale Anforderungen>>

== Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

== Aufgabenstellung und Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.

== Produktnutzung
In welchem Kontext soll das System später genutzt werden? Welche Rahmenbedingungen gelten?
Zusätzlich kurze Einleitung für fachfremde Personen


Die Website des Cateringservice Mampf soll übersichtlich und informativ die unterschiedlichen Angebote der Firma an die Kunden bringen. Neben den gebotenen Informationen, soll es Kunden möglich sein, ein Event ohne großen Aufwand zu buchen. 
Bei der Zielgruppe handelt es sich sowohl um Firmen, die in der Lage sind, ohne große Probleme eine Website zu navigieren, als auch um Privatpersonen, die Feiern für verschiedene private Anlässe organisieren wollen, bei denen technisches Wissen nicht zwingend vorauszusetzen ist.

Die Website ist vor allem für die Nutzung am Computer vorgesehen und für folgende Browser optimiert: 

- Google Chrome, Version 95.0.4638.54+
- Mozilla Firefox, Version	93.0+

Die Software soll ohne Wartungsarbeiten konstant laufen und alle gespeicherten Daten sollen für den Betreiber ohne technisches Wissen über die Webseite abrufbar sein.

== Interessensgruppen (Stakeholders)
Welche realen und juristischen Personen(-gruppen) haben Einfluss auf die Anforderungen im Projekt?

== Systemgrenze und Top-Level-Architektur

=== Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

== Anwendungsfälle

Anwendungsfälle beschreiben welche Interaktionen der Nutzer mit dem System durchführen kann, welche Funktionalität das System dabei erfüllen muss und welche Akteure beteiligt sind.

=== Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name
|Beschreibung

|Nutzer
|Steht für alle Nutzer, die mit der Software interagieren, egal ob registriert oder nicht.

|Unregistrierter Nutzer
|Steht für alle nicht registrierten und nicht angemeldeten Nutzer.

|Angemeldeter Nutzer
|Steht für alle Nutzer, die einen Account registriert haben, und angemeldet sind.

|Kunde
|Steht für alle angemeldeten Nutzer, die die Rolle “CUSTOMER” haben und somit Bestellungen tätigen können.

|Personal
|Steht für alle angemeldeten Nutzer, die die Rolle “STAFF” haben, und somit die eingegangenen Bestellungen einsehen können.

|Administrator
|Steht für alle angemeldeten Nutzer, die die Rolle “ADMIN” haben, und somit das System vollständig verwalten können.
|===

=== Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

== Funktionale Anforderungen

=== Muss-Kriterien
Was das zu erstellende Programm auf alle Fälle leisten muss.

=== Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

== Nicht-Funktionale Anforderungen
Dieses Kapitel gibt einen Überblick über die Nicht-Funktionalen Anforderungen. Diese beinhalten Qulitätsattribute, ohne die eine der Nutzergruppen benachteiligt wird. Beispielsweise die Bedienbarkeit oder die Sicherheit.

=== Qualitätsziele

Die folgende Tabelle zeigt die zu erreichenden Qualitätsziele im System und ihre Priorität.

1 = Nicht wichtig ...
5 = Am wichtigsten

[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Qualitätsziel           | 1 | 2 | 3 | 4 | 5 
|Wartbarkeit             |   | x |   |   |
|Bedienbarkeit           |   |   |   | x |
|Sicherheit              |   |   |   | x |
|===

=== Konkrete Nicht-Funktionale Anforderungen

Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.

[options="header", cols="h, ^1, ^1, ^1"]
|===
|ID         |Version | Name          | Beschreibung
|[NF010]    |0.1     |Wartbarkeit    | Das System soll mit einer ausreichenden Developerdokumentation geliefert weden.
|[NF020]    |0.1     |Bedienbarkeit  | Die Benutzeroberflächen sollen pbersichtlich sein. Knöpfe und Forms sollen gut zusammengestellt und weisen eine einfache Bedienung aller Nutzergruppen aus
|[NF030]    |0.1     |Autorität     | Die Systemnutzer sollen nicht mehr Zugriffsrechte haben als die, die bei der Kontoerstellung angegeben wurden. Bei sehr großen Bestellungen soll dem Nutzer daraut hingewiesen werden, dass die Bestellung vor Ort abgeschlossen werden muss
|===

== GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== Datenmodell

=== Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.


[cols="1h, 4"]
|===
|ID                  |<<AT000>>
|Anwedungsfall       |<<UC00>>
|Voraussetzung       a|Das System hat Nutzer.
|Event               a|Ein unregistrierter Nutzer befindet sich auf der “Anmelden”-Seite, gibt dort E-Mail-Adresse und Passwort ein, die mit den Daten eines registrierten Nutzers übereinstimmen (hannes.wurst@mampf.de, cAt3r1nG_yeay) und klickt “Anmelden”.
|Erwartetes Resultat a|
- Der Nutzer ist nun angemeldet als “hannes.wurst@mampf.de”
- Der Nutzer wird zur Startseite weitergeleitet
- Der Nutzer hat Zugriff zu allen Funktionen, die der Rolle “CUSTOMER” zugeordnet sind.
|===

[cols="1h, 4"]
|===
|ID                  |<<AT001>>
|Anwedungsfall       |<<UC00>>
|Voraussetzung       a|Ein angemeldeter Nutzer nutzt das System.
|Event               a|Der angemeldete Nutzer klickt “Ausloggen”.
|Erwartetes Resultat a|
- Der Nutzer ist abgemeldet
- Der Nutzer verliert den Zugriff auf alle Funktionalitäten, die der Rolle “CUSTOMER” zugeordnet sind.
|===

[cols="1h, 4"]
|===
|ID                  |<<AT010>>
|Anwedungsfall       |<<UC01>>
|Voraussetzung       a|Ein unregistrierter Nutzer nutzt das System.
|Event               a|Der nicht registrierte Nutzer klickt “Registrieren” und gibt die folgenden Informationen ein:

- Name: Test Kunde
- E-Mail-Adresse: test@kunde.com
- Passwort: irgendWAS_123

Um die Registrierung abzuschließen klickt der Nutzer “Registrieren”
|Erwartetes Resultat a|
- Es wird ein neues Kundenkonto mit den angegeben Daten erstell
- Es ist nun möglich sich mit der angegebenen E-Mail-Adresse und dem Passwort anzumelden
- Der unangemeldete Nutzer ist immer noch unangemeldet und wird auf die Startseite weitergeleitet
|===

[cols="1h, 4"]
|===
|ID                  |<<AT011>>
|Anwedungsfall       |<<UC01>>
|Voraussetzung       a|Ein unregistrierter Nutzer nutzt das System.
|Event               a|Der nicht registrierte Nutzer klickt “Registrieren” und gibt die folgenden Informationen ein:

- Name: Hannes Wurst
- E-Mail-Adresse: test@kunde.com
- Passwort: cAt3r1nG_yeay

Um die Registrierung abzuschließen klickt der Nutzer “Registrieren”
|Erwartetes Resultat a|
- Dem Nutzer wird eine Fehlermeldung angezeigt die ihn informiert, dass ein Nutzer mit dieser E-Mail-Adresse bereits existiert
|===

[cols="1h, 4"]
|===
|ID                  |<<AT100>>
|Anwedungsfall       |<<UC11>>
|Voraussetzung       a|Ein Nutzer nutzt das System.
|Event               a|Der Nutzer klickt in der Navigationsleiste auf “Angebot”.
|Erwartetes Resultat a|Dem Nutzer werden die angebotenen Dienstleistungen ‘Eventcatering’, ‘Partyservice’, ‘Mobile Breakfast’ und ‘Rent-a-cook’ mit einer kurzen Beschreibung vorgestellt.
|===

[cols="1h, 4"]
|===
|ID                  |<<AT101>>
|Anwedungsfall       |<<UC02>>
|Voraussetzung       a|Ein angemeldeter Nutzer benutzt das System.
|Event               a|Der Nutzer klickt auf den Menüpunkt “Profil”.
|Erwartetes Resultat a|Der Nutzer erlangt (auf einer neuen Seite) einsicht auf die Daten, die er beim registrieren angegeben hat und kann diese bearbeiten.
|===

[cols="1h, 4"]
|===
|ID                  |<<AT111>>
|Anwedungsfall       |<<UC03>>
|Voraussetzung       a|Ein angemeldeter Nutzer benutzt das System und befindet sich auf seinem Profil.
|Event               a|Der Nutzer klickt auf "Account löschen".
|Erwartetes Resultat a|- Das Benutzerkonto wird aus dem System entfernt
- Der Nutzer verliert seine Rolle "CUSTOMER"
- Der nun unregistrierter  Nutzer wird zurück zur Startseite geleitet
|===

[cols="1h, 4"]
|===
|ID                  |<<AT002>>
|Anwedungsfall       |<<UC20>>
|Voraussetzung       a|Ein angemeldeter Nutzer benutzt das System und befindet sich am Ende auf einer der vier Angebotsseiten.
|Event               a|Der Nutzer klickt auf "Bestellen".
|Erwartetes Resultat a|Dem Nutzer wird auf einer neuen Seite das Bestellformular für seine Dienstleistung angezeigt.
|===



== Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
