= Zeiterfassung für Gruppe 27

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Dan |Konrad |Lennart |Lisa |Mohamad |Rosa |Meeting
|1  |240   |180  |210    |300    |90    |180    |60   
|2  |480   |540   |540    |610    |450    |570  |250
|3  |540  |540   |840    |500    |480    |600    |430
|4  |480   |480  |510    |650    |1080    |630    |75
|5  |600   |660 |840    |530    |600    |540    |660
|6  |660   |420   |360    |430    |840    |480    |300
|7  |840   |600    |480    |560    |1200    |450    |15
|8  |1200   |720    |450    |520    |780    |480    |15
|9  |540   |660   |600    |430    |400    |360    |15
|10  |180   |120    |210    |160    |540    |90    |150
|11  |120   |120    |90    |90    |600   |160    |15
|12  |…   |60    |120    |100    |0    |…    |200
|Stunden gesamt*  |98   |84    |88    |81    |118    |76    |36
|Stunden pro Woche pro Student  |8   |7    |7    |7    |10    |6    |-
|Durchschnitt 6+|8 |-
|===

{asterisk} Werte sind auf nächste ganze Zahl gerundet

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
